# Generated by Django 3.0.7 on 2020-06-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=10, verbose_name='марка автомобиля')),
                ('car_model', models.CharField(max_length=10, verbose_name='модель автомобиля')),
                ('year_of_issue', models.SmallIntegerField(default=2018, verbose_name='год выпуска')),
                ('transmission', models.SmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')], default=1)),
                ('color', models.CharField(max_length=25, verbose_name='цвет автомобиля')),
            ],
        ),
    ]
