# Generated by Django 3.0.7 on 2020-06-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0003_auto_20200613_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
